apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: postgres-295devops
    type: database-295devops
spec:
  type: ClusterIP
  ports:
  - name: service-postgres
    port: 5432
    targetPort: db-port
  selector:
    app: postgres
    type: database
